env:
  browser: true
  commonjs: true
  es2021: true
  greasemonkey: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
plugins:
  - '@typescript-eslint'
ignorePatterns: 
  - dist/**.js
rules:
  semi:
    - error
    - always